FROM python:3.8-slim-buster

# Open http port
EXPOSE 8000

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV DEBIAN_FRONTEND noninteractive

WORKDIR /app/figures_api
COPY requirements.txt /app/figures_api
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/figures_api

CMD sh -c "python manage.py migrate && gunicorn -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker api.asgi:application"
