version: "3"

services:
  backend:
    build: 
      dockerfile: Dockerfile.backend
      context: ./figures_api
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./figures_api:/app
    ports:
      - "8003:8000"

  web:
    build: 
      dockerfile: Dockerfile.frontend
      context: ./web
    ports:
      - "3000:3000"
    command: bash -c "npm run start"