version: "3"

services:
  backend:
    build: 
      dockerfile: figures_api/Dockerfile.dev
      context: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8003:8000"
      - "8004:8001"
    links:
      - redis

  web:
    build: 
      dockerfile: Dockerfile.frontend
      context: ./web
    ports:
      - "3000:3000"
    command: bash -c "npm run start"

  redis:
    image: redis:7
    ports:
      - "6379:6379"